# This configuration sets up DNS traffic monitoring through DNStap on port 6000;
# applies transformations on it and send to the console and prometheus

# If turned on, debug messages are printed in the standard output
global:
  trace:
    verbose: true

pipelines:
  - name: tap
    dnstap:
      listen-ip: 0.0.0.0
      listen-port: 6000
    transforms:
      latency:
        measure-latency: false
        unanswered-queries: true
        queries-timeout: 2
    routing-policy:
      forward: [ console, prom ]

  - name: console
    stdout:
      mode: text

  - name: prom
    prometheus:
      listen-ip: 0.0.0.0
      listen-port: 8080