name: Go Benchmark

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
    branches:
      - main

permissions:
  contents: read

jobs:
  dev:
    strategy:
      matrix:
        os-version: [ 'ubuntu-24.04' ]
        go-version: [ '1.24'  ]
    runs-on: ${{ matrix.os-version }}

    steps:
    - uses: actions/checkout@v5

    - name: Configure environment to avoid toolchain installs 
      shell: bash
      run: echo "GOTOOLCHAIN=local" >> "$GITHUB_ENV"

    - uses: actions/setup-go@v5
      with:
        go-version: "${{ matrix.go-version }}"

    - name: Show Go version
      run: |
        go version

    - name: Bench dnsutils
      run: |
        cd dnsutils/
        go test -benchmem -run=^$ -bench=.
    
    - name: Bench transformers
      run: |
        cd transformers/
        go test -benchmem -run=^$ -bench=^BenchmarkUserPrivacy.*\|BenchmarkTransforms.*\|BenchmarkNormalize.*$