name: Go Linter

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
    branches:
      - main

permissions:
  contents: read # for actions/checkout to fetch code
  pull-requests: read  # for golangci/golangci-lint-action to fetch pull requests

env:
  GO_VERSION: "1.24"
  GOLANGCI_LINT_VERSION: "v2.1.6"
  
jobs:
  linter:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: "${{ env.GO_VERSION }}"
        # workaround: when the files to be extracted are already present, 
        # tar extraction in Golangci Lint fails with the "File exists"
        # https://github.com/golangci/golangci-lint-action/issues/807
        cache: false

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: "${{ env.GOLANGCI_LINT_VERSION }}"
        args: --timeout 3m --verbose
 