name: Go Releaser
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

env:
  GO_VERSION: "1.24"

jobs:
  goreleaser:
    permissions:
      contents: write  # for goreleaser/goreleaser-action to create a GitHub release
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GO_VERSION }}"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          name: ${{github.ref_name}}
          tag_name: ${{github.ref_name}}
          files: |
            docker-compose.yml
            docker-example.env