name: Docker Push

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:

  dockerhub:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: |
        docker build --build-arg VERSION=${{ github.event.release.tag_name }} . --file Dockerfile -t dnscollector

    - name: Tag image
      run: |
        docker tag dnscollector dmachard/dnscollector:${{ github.event.release.tag_name }}
        docker tag dnscollector dmachard/dnscollector:latest
        docker tag dnscollector dmachard/go-dnscollector:${{ github.event.release.tag_name }}
        docker tag dnscollector dmachard/go-dnscollector:latest

    - name: Upload to DockerHub
      run: |
        echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_LOGIN }}" --password-stdin
        docker push dmachard/dnscollector:latest
        docker push dmachard/dnscollector:${{ github.event.release.tag_name }}
        docker push dmachard/go-dnscollector:latest
        docker push dmachard/go-dnscollector:${{ github.event.release.tag_name }}
