name: Tests PowerDNS

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
    branches:
      - main

permissions:
  contents: read

env:
  PYTHON_VERSION: "3.13"
  GO_VERSION: "1.24"

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GO_VERSION }}"

      - name: Build Binary
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o dnscollector *.go

      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dnscollector
          path: dnscollector

  test_protobuf:
    needs: build
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        component: 
          - { name: 'dnsdist', version: '18' }
          - { name: 'dnsdist', version: '19' }
          - { name: 'dnsdist2', version: '20' }
          - { name: 'recursor', version: '51' }
          - { name: 'recursor', version: '52' }

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v5
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: Download Binary Artifact
        uses: actions/download-artifact@v5
        with:
          name: dnscollector

      - name: Make Binary Executable
        run: chmod +x dnscollector

      - name: Deploy Docker image
        run: |
          case ${{ matrix.component.name }} in
            "dnsdist")
              sudo docker run -d --network="host" --name=dnsdist --volume=$PWD/tests/testsdata/powerdns/dnsdist_protobuf.conf:/etc/dnsdist/conf.d/dnsdist.conf:z -v /tmp/:/tmp/ powerdns/dnsdist-${{ matrix.component.version }}
              ;;
            "dnsdist2")
              sudo docker run -d --network="host" --name=dnsdist --volume=$PWD/tests/testsdata/powerdns/dnsdist2_protobuf.yml:/etc/dnsdist/dnsdist.yml:z powerdns/dnsdist-${{ matrix.component.version }}  -C /etc/dnsdist/dnsdist.yml
              ;;
            "recursor")
              sudo docker run -d --network="host" --name=recursor --volume=$PWD/tests/testsdata/powerdns/pdns_recursor.yml:/etc/powerdns/recursor.yml:z powerdns/pdns-recursor-${{ matrix.component.version }}
              ;;
          esac
          until (dig -p 5553 www.github.com @127.0.0.1 | grep NOERROR); do sleep 5.0; done

      - name: Test DNS query
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python3 -m pip install dnspython
          python3 -m unittest tests.dnsquery_powerdns -v
